### ISSUE TITLE
Requisitos 

### ISSUE THREAD

**Issue by angoti** [angoti/Cantinho-do-Cerrado-#1]
Levantar requisitos iniciais do app

**Comment by angoti** [comment]
Propósito -> qual o objetivo de desenvolver o app
O que o app faz? quais as funcionalidades

1- exibir fotos de parques
2- exibir informações sobre os parques: localização, 
3-

**Comment by angoti** [comment]
![Image](https://github.com/user-attachments/assets/e3569062-373a-4d1b-bec8-a3e8e33f4d36)

**Comment by AnnerGabrii** [comment]
Ideias:Reserva educacional
Rotas dos locais para beber agua 
Cabeçalho
Filtragem por atividades(Ex: selecionar  "andar de bicicleta" nas opções de atividade vai logo após ira aparecer os parques que ocorrem essa atividade).
Adicionar seu parque de preferência nos favoritos
Acessibilidade(indicar os parques que tem mobilidade reduzida ou necessidades especiais.

**Comment by JoaoVitorArantes** [comment]
1. Mapas: Exibição de mapas dos parques com trilhas, pontos de interesse, banheiros, áreas de piquenique 

2. Informações: Histórico, horários de funcionamento, regras do parque 

3. Agenda de Eventos: Calendário de eventos, atividades programadas, passeios guiados e outras atividades

4. Notificações: Alertas sobre mudanças de horário, eventos especiais, condições climáticas, entre outros

5. Guia de Fauna e Flora: Banco de dados com informações e fotos das espécies encontradas nos parques

6. Avaliações e Comentários: Seção para que os visitantes deixem avaliações e comentários sobre suas experiências

7. Jogos Educativos(ideia bem pra frente): Jogos e quizzes para educar os visitantes sobre a preservação do meio ambiente e a biodiversidade do Cerrado

8. Redes Sociais: Integração com redes sociais para que os visitantes possam compartilhar fotos e experiências diretamente do aplicativo

9. Trilhas e Caminhadas: Descrição e dificuldade das trilhas, com orientação por GPS e falar do tempo e distância percorrida

10. Contato: Contato direto com a administração dos parques, suporte

11. Sustentabilidade: educação por dicas de sustentabilidade, coleta seletiva e práticas ecológicas para os visitantes


Ideias pro nosso App

**Comment by angoti** [comment]
**Requisitos não funcionais**
-Modo escuro
- Redes Sociais: Integração com redes sociais para que os visitantes possam compartilhar fotos e experiências diretamente do aplicativo
- Barra de mavegação (inferior ou superior)
-Tela de login

**Requisitos funcionais**
1- Parques
-  exibir fotos do parque
- exibir informações sobre os parques: endereço, localização, exibir rotas, histórico, horários de funcionamento, valor de atividades pagas, 
regras do parque
- Mapas: Exibição de mapas dos parques com trilhas, pontos de interesse, banheiros, áreas de piquenique
- Contato: Contato direto com a administração dos parques, suporte
- Reserva educacional
- Favoritar ao parque de preferência 
- Acessibilidade(indicar os parques que tem mobilidade reduzida ou necessidades especiais.

2- Pesquisa

3- Agenda de Eventos: Calendário de eventos, atividades programadas, passeios guiados e outras atividades

4 - Notificações: Alertas sobre mudanças de horário, eventos especiais, condições climáticas, entre outros. Sistema de alertas de segurança em tempo real para situações como incêndios florestais, evacuações de emergência, presença de animais perigosos, etc

5- Guia de Fauna e Flora: Banco de dados com informações e fotos das espécies encontradas nos parques

6 - Avaliações e Comentários: Seção para que os visitantes deixem avaliações e comentários sobre suas experiências

7 - Jogos Educativos(ideia bem pra frente): Jogos e quizzes para educar os visitantes sobre a preservação do meio ambiente e a biodiversidade do Cerrado

8- Trilhas e Caminhadas: Descrição e dificuldade das trilhas, com orientação por GPS e falar do tempo e distância percorrida

9- Educação ambiental e Sustentabilidade: educação por dicas de sustentabilidade, coleta seletiva e práticas ecológicas para os visitantes. Dicas e recursos sobre práticas sustentáveis para visitantes e para a administração do parque, como uso eficiente de recursos naturais, energia renovável, gestão de resíduos e iniciativas de eco-friendly

10- Integração de funcionalidades de realidade aumentada para oferecer aos usuários experiências interativas, como identificação de espécies de plantas e animais, informações históricas sobre pontos de interesse no parque, entre outros
